apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image:
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8000
